export enum tipoInstruccion {
    IMPRIMIR,
    DECLARACION_VARIABLE,
    REASIGNACION,
    BLOQUE,
    SI,
    WHILE,
    PARA,
    FUNCION,
    CREAR_OBJETOS,
    INCREMENTO,
    DECREMENTO,
    MIENTRAS,
    HACER_HASTA_QUE,
    DETENER,
    CONTINUAR,
    PROCEDIMIENTO
}